# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: usildevops/mssql-docker-enhanced
    container_name: mssql-db
    volumes: 
      # - ./sql:/docker-entrypoint-initdb.d
      - ./dbdata:/var/opt/mssql/data
    restart: always
    ports: 
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_USER: sa
      MSSQL_SA_PASSWORD: 'MyStrongPassword123'
    healthcheck:
      test: cat /var/log/docker/sqlserver_db_init.log | grep [db_init_completed]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s 